#!/usr/bin/perl -w

=pod

=head1 Name

moonsig - a continually changing signature based on the phase of the moon

=head2 License

Copyright 2010 Neil Kandalgaonkar.

This work is licensed under the terms of the GNU General Public License, 
version 2 or later. 
(see http://www.fsf.org/licensing/licenses/gpl.html). 
Derivative works and later versions of the code must be free software 
licensed under the same or a compatible license.

=cut

use strict;

use Astro::MoonPhase qw/phase/;

my $address = $ARGV[0];

my ($phase, @dummy) = phase();
my $display = " * ";

if ($phase >= 0.95 or $phase < 0.05) {
  $display = "   ";
} elsif ($phase >= 0.05 and $phase < 0.25) {
  $display = "  )";
} elsif ($phase >= 0.25 and $phase < 0.45) {
  $display = " |)";
} elsif ($phase >= 0.45 and $phase < 0.55) {
  $display = "( )";
} elsif ($phase >= 0.55 and $phase < 0.75) {
  $display = "(| ";
} elsif ($phase >= 0.75 and $phase < 0.95) {
  $display = "(  ";
} else {
  die "impossible? phase = $phase";
}

print <<EOF;
-- 
Neil Kandalgaonkar $display <$address>
EOF
